### ISSUE TITLE
How to complete the experiment on pope?

### ISSUE THREAD

**Issue by Mr-xiu** [CRIPAC-DIG/LogicCheckGPT#1]
I am confused about how to correct the answer on the pope dataset. As far as I know, the answer on the pope dataset is only yes or no.

**Comment by Mr-xiu** [comment]
I am confused about how to correct the answer on the pope dataset. As far as I know, the answer on the pope dataset is only yes or no.

**Comment by Hyperwjf** [comment]
Hi! In our experiments, we have observed that the responses from the four LVLMs to POPE questions are in the format as "Yes/No, there is/isn't {object} ..." This format allows us to effectively extract the examinee object. For instance, the responses of mPLUG-Owl to some POPE questions are listed below:

![issue_1](https://github.com/Hyperwjf/LogicCheckGPT/assets/62200664/d6f3760d-ffe3-4dd4-a1e7-43847d6b150b)

The responses of LLaVA-1.5 to some POPE questions are listed below:
![image](https://github.com/Hyperwjf/LogicCheckGPT/assets/62200664/77014ff1-8a55-4bb7-8add-95876e4ab608)


However, to circumvent instances where LVLMs provide a single "Yes" or "No" response, we propose to adopt a strategy following Woodpecker[1]:  "(1) we first extract keywords, i.e., “Yes” and “No” from the responses as the answers, then combine the questions with the answers into more specific claims."

[1] Woodpecker: Hallucination Correction for Multimodal Large Language Models

**Comment by Mr-xiu** [comment]
> Hi! In our experiments, we have observed that the responses from the four LVLMs to POPE questions are in the format as "Yes/No, there is/isn't {object} ..." This format allows us to effectively extract the examinee object. For instance, the responses of mPLUG-Owl to some POPE questions are listed below:
> 
> ![issue_1](https://private-user-images.githubusercontent.com/62200664/313522376-d6f3760d-ffe3-4dd4-a1e7-43847d6b150b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODg3ODIsIm5iZiI6MTcxMTA4ODQ4MiwicGF0aCI6Ii82MjIwMDY2NC8zMTM1MjIzNzYtZDZmMzc2MGQtZmZlMy00ZGQ0LWExZTctNDM4NDdkNmIxNTBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA2MjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZGFmMjZjYTE4NjNmOTU5NGRmNTg1MTFmMmQ1NjUxZmY3YjY4ZjM3ZTU4ZWE2OWMxMWY2YjRlOTc3YWQ3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PeQjUqe8pn51i_6izgQo5H9Uy8CDotALxyxh4fWbvv0)
> 
> The responses of LLaVA-1.5 to some POPE questions are listed below: ![image](https://private-user-images.githubusercontent.com/62200664/313526112-77014ff1-8a55-4bb7-8add-95876e4ab608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODg3ODIsIm5iZiI6MTcxMTA4ODQ4MiwicGF0aCI6Ii82MjIwMDY2NC8zMTM1MjYxMTItNzcwMTRmZjEtOGE1NS00YmI3LThhZGQtOTU4NzZlNGFiNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA2MjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MTc1MTkwZWI1ZmE1YjY1MzhhYjU1YTIyYmVhYTQxNmU5ZDVkMmY1YzRkYzUyN2IxOTViNjQwMTMzMjIwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.InSAzy7bS6GmDIcfEoi1M1ggkcriglenVtMUzSDiqp0)
> 
> However, to circumvent instances where LVLMs provide a single "Yes" or "No" response, we propose to adopt a strategy following Woodpecker[1]: "(1) we first extract keywords, i.e., “Yes” and “No” from the responses as the answers, then combine the questions with the answers into more specific claims."
> 
> [1] Woodpecker: Hallucination Correction for Multimodal Large Language Models

Thank you very much for your answer!
